ChoixResto/ViewModels/PresentationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ChoixResto.ViewModels
{
    public class PresentationViewModel
    {
        [Display(Name = "Le message")]
        public string Message { get; set; }
        public Models.Restaurant Restaurant {get;set;}
        public DateTime Date { get; set; }
        [MaxLength(5, ErrorMessage = "Login charactères insuffisant")]
        public string Login { get; set; }
    }
}

ChoixResto/Controllers/AccueilController.cs
using ChoixResto.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChoixResto.Controllers
{
    public class AccueilController : Controller
    {
        private IDal dal;
        public AccueilController():this(new Dal()) { }
        public AccueilController(IDal dalIoc)
        {
            dal = dalIoc;
        }

        public ActionResult Index()
        {
            return View();
        }
        
        [HttpPost]
        [ActionName("Index")]
        public ActionResult IndexPost()
        {
            int idSondage = this.dal.CreerUnSondage();
            return RedirectToAction("Index", "Vote", new { Id = idSondage });
        }

       
    }
}

ChoixResto/Controllers/RestaurantController.cs
using ChoixResto.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChoixResto.Controllers
{
    public class RestaurantController : Controller
    {
            private IDal dal;

            public RestaurantController() : this(new Dal())
            {
            }

            public RestaurantController(IDal dalIoc)
            {
                dal = dalIoc;
            }

            public ActionResult Index()
            {
                List<Restaurant> listeDesRestaurants = dal.ObtenirListeResto() ;
                return View(listeDesRestaurants);
            }

            public ActionResult CreerRestaurant()
            {
                return View();
            }

            [HttpPost]
            public ActionResult CreerRestaurant(Restaurant resto)
            {
                if (dal.RestaurantExiste(resto.Nom))
                {
                    ModelState.AddModelError("Nom", "Ce nom de restaurant existe déjà");
                    return View(resto);
                }
                if (!ModelState.IsValid)
                    return View(resto);
                dal.CreerResto(resto.Nom, resto.Telephone);
                return RedirectToAction("Index");
            }

            public ActionResult ModifierRestaurant(int? id)
            {
                if (id.HasValue)
                {
                    Restaurant restaurant = dal.ObtenirListeResto().FirstOrDefault(r => r.Id == id.Value);
                    if (restaurant == null)
                        return View("Error");
                    return View(restaurant);
                }
                else
                    return HttpNotFound();
            }

        [HttpPost]
        public ActionResult ModifierRestaurant(Restaurant resto)
        {
            if (!ModelState.IsValid)
                return View(resto);
            dal.ModifierLesRestos(resto.Id, resto.Nom, resto.Telephone, resto.Email);
            return RedirectToAction("Index");
        }  
    }
}

        

ChoixResto/Views/Accueil/Index.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        
       <h1>Bienvenue au restaurant</h1>
        <p>Prêt à choisir un restaurant ?</p>
        
        @Html.ActionLink("Créer un restaurant","CreerRestaurant", "Restaurant")
        <br/>
        @Html.ActionLink("Modifier les restaurants", "Index", "Restaurant")
        @using (Html.BeginForm())
        {
            <button  type="submit" >Créer un sondage</button>
        }
        @if (HttpContext.Current.User.Identity.IsAuthenticated)
        {
            @Html.ActionLink("Déconnexion", actionName: "Signout", controllerName: "Login")
        }
             
    </div>
</body>
</html>

ChoixResto/Views/Accueil/Presentation.cshtml
@model ChoixResto.ViewModels.PresentationViewModel
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Presentation restaurant @Model.Restaurant.Nom</title>
    <style>
        .maClass {
            color: brown;
        }
    </style>
</head>
<body>
    <div> 
       
        <p>Voici la page de présenation du resto' @Model.Restaurant.Nom</p>
        <br/>
        <p>Nous avons ouvert le @Model.Date</p>
        <p>N'hésitez pas à nous contacter au @Model.Restaurant.Telephone</p>


        @Html.Label("participer", "Voulez-vous participer ?", new { style = "color: black" })
        @Html.CheckBox("participer", true)
        @Html.Label("textCouleur", "Affichage par classe marron", new { @Class = "maClass" })
        <br/><br/>
        @Html.DropDownList("RestoChoisi", (SelectList)ViewBag.ListeResto)<!-- selectlist -->
        <!-- HELPER FORM -->
        @{Html.BeginForm("Index", "Accueil");}
        @Html.Label("nom", "Votre nom")
        <input id="nom" maxlength="20" />
        <input type="submit" value="Envoyer" />
        @{Html.EndForm();}
        <!-- link affichage, méthode, controller, paramètre get -->
        @Html.ActionLink("Accueil", "ActionLink", "Accueil", new { id = Model.Restaurant.Id }, null)
    
    
        <!-- partial vue avec passage du modèle en paramètre -->
        @Html.Partial("Connexion", Model)
    </div>
</body>
</html>