ChoixResto/Controllers/LoginController.cs
using ChoixResto.Models;
using ChoixResto.ViewModels;
using System.Web.Security;
using System.Web.Mvc;

namespace ChoixResto.Controllers
{
    public class LoginController : Controller
    {
        private IDal dal;
        public LoginController(): this(new Dal()) { }
        public LoginController(IDal dal)
        {
            this.dal = dal;
        }
        // GET: Login
        public ActionResult Index()
        {
            ViewModels.UtilisateurViewModel viewModel = new ViewModels.UtilisateurViewModel() { Authentifie = HttpContext.User.Identity.IsAuthenticated };
            if(HttpContext.User.Identity.IsAuthenticated)
            {
                viewModel.Utilsateur = dal.ObtenirUtilisateur(HttpContext.User.Identity.Name);
            }
            return View(viewModel);
        }
        [HttpPost]
        public ActionResult Index(UtilisateurViewModel viewModel, string ReturnUrl)
        {
            if (ModelState.IsValid)
            {
                Utilisateur user = this.dal.Authentifier(viewModel.Utilsateur.Prenom, viewModel.Utilsateur.MotDePasse);
                if(user != null)
                {
                    System.Web.Security.FormsAuthentication.SetAuthCookie(user.Id.ToString(), false);
                    return Redirect(ReturnUrl);
                }
                ModelState.AddModelError("Utilsateur.Prenom", "Utilisateur non reconnu");
            }
                return View(viewModel);
           
        }

        public ActionResult CreerCompte()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreerCompte(ViewModels.CreerCompteUtisateurViewModel user)
        {
            if(ModelState.IsValid)
            {
                int id = this.dal.AjouterUtilisateur(user.Prenom, user.MotDePasse);
                FormsAuthentication.SetAuthCookie(id.ToString(), false);
                return Redirect("/");
            }
            return View(user);
        }
        [HttpGet]
        public ActionResult Signout()
        {
            FormsAuthentication.SignOut();
            return Redirect("/");
        }
    }
}

ChoixResto/Views/Login/CreerCompte.cshtml
@model ChoixResto.ViewModels.CreerCompteUtisateurViewModel
@{
    ViewBag.Title = "Création de compte";
    Layout = "~/Views/Shared/_Global.cshtml";
}
@section Js
{
    <script type="text/javascript" src="~/scripts/jquery-1.7.1.js"></script>
    <script type="text/javascript" src="~/scripts/jquery.validate-vsdoc.js"></script>
    <script type="text/javascript" src="~/scripts/jquery.validate.unobtrusive.js"></script>
}

<h2>Créer compte</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ajout d'utilisateur</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Prenom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Prenom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prenom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MotDePasse,  htmlAttributes: new { @class = "control-label col-md-2" }, labelText: "Mot de passe :")
            <div class="col-md-10">
                @Html.PasswordFor(model => model.MotDePasse, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MotDePasse, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.MotDePasseVerif, htmlAttributes: new { @class = "control-label col-md-2" }, labelText: "Vérification :")
            <div class="col-md-10">
                @Html.PasswordFor(model => model.MotDePasseVerif, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MotDePasseVerif, "", new { @class = "text-danger" })
            </div>
            
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Créer l'utilisateur" class="btn btn-default" />
            </div>
        </div>
    </div>
}

ChoixResto/Views/Login/Index.cshtml
@model ChoixResto.ViewModels.UtilisateurViewModel
@{
    ViewBag.Title = "Connexion";
    Layout = "~/Views/Shared/_Global.cshtml";
}

@if(Model.Authentifie)
{
    <p>Vous êtes authentifié avec le pseudo @Model.Utilsateur.Prenom
    <br/>
       @Html.ActionLink("Déconnexion", "Logout", "Login")
    </p>
}
else
{
    using (Html.BeginForm())
    {
        @Html.LabelFor(u => u.Utilsateur.Prenom, "Pseudo :")
        @Html.TextBoxFor(u => u.Utilsateur.Prenom)
        @Html.ValidationMessageFor(u => u.Utilsateur.Prenom)<br />

        @Html.LabelFor(u => u.Utilsateur.MotDePasse, "Mot de passe :")
        @Html.PasswordFor(u => u.Utilsateur.MotDePasse)
        <br />
        <input type="submit" value="Se connecter" />
        @Html.ActionLink("Créer un compte", "CreerCompte", "Login")
    }
}